name: Test macOS image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./processes-with-open-windows
    - uses: OrbitalOwen/desktop-screenshot-action@0.1
      if: failure()
      with:
        file-name: desktop.jpg
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        path: desktop.jpg
